const tempTypes = {
  FETCH_TEMPLATES_START: "FETCH_TEMPLATES_START",
  FETCH_TEMPLATES_SUCCESS: "FETCH_TEMPLATES_SUCCESS",
  FETCH_TEMPLATES_FAILURE: "FETCH_TEMPLATES_FAILURE",
};

export default tempTypes;
