 const filterTypes = {
	CHANGE_FILTER_INPUT_VALUE: 'CHANGE_FILTER_INPUT_VALUE',
	CLEAR_FILTER_INPUT_VALUE: 'CLEAR_FILTER_INPUT_VALUE',
	FETCH_FILTER_RESULTS_REQUEST: 'FETCH_FILTER_RESULTS_REQUEST',
	FETCH_FILTER_RESULTS_SUCCESS: 'FETCH_FILTER_RESULTS_SUCCESS',
	FETCH_FILTER_RESULTS_FAILURE: 'FETCH_FILTER_RESULTS_FAILURE',
}

export default filterTypes